#!/usr/bin/env python

import os, sys

for path, dirs, files in os.walk("."):
   if path.find(".svn") == -1:
      for file in files:
         if file.find(".cpp") != -1 or file.find(".h") != -1 or file.find(".glsl") != -1:
            inlic = True
            wrotelic = False
            firstline = True
            f = open(path + "/" + file)
            tempfile = open("/tmp/lictemp", 'w')
            for line in f:
               if not wrotelic:
                  licfile = open("license")
                  for licline in licfile:
                     tempfile.write(licline)
                  licfile.close()
                  wrotelic = True
               
               if firstline:
                  if line.find("// @Begin License@") == -1:
                     inlic = False
                  firstline = False
               
               if not inlic:
                  tempfile.write(line)
               
               if line.find("// @End License@") != -1:
                  inlic = False
            tempfile.close()
            f.close()
            # For whatever reason this doesn't work
            #os.rename("/tmp/lictemp", "./" + file)
            os.system("mv /tmp/lictemp " + path + "/" + file)
         