#!/bin/bash
svn commit *.h *.cpp gui/*.xml *.sh *.py maps textures/* models/ fonts/* shaders/* gui/*.cpp gui/*.h materials/* weapons/* items/* particles/* units/ sounds/* commitall Makefile startscript license applylicense convert
