#!/bin/bash

count=0

for i in `seq 0 50 900`
do
   for j in `seq 0 50 700`
   do
      count=$(($count+1))
      # Tristrip
      #echo tristrip
      #echo 7
      #echo 0 0 0
      #echo $i 100 $j
      #echo $i 100 $(($j+10))
      #echo $(($i+10)) 100 $j
      #echo $(($i+10)) 100 $(($j+10))
      #echo 0 0 0

      # Tree
      echo tree
      echo 9 10 11
      echo 10 5 100 25 10
      echo $i -1 $j
      echo 0 0 0
      echo 10
      echo
   done
done

echo $count
